### ISSUE TITLE
Track hiking as a category of cardio report

### ISSUE THREAD

**Issue by njbbaer** [njbbaer/self-metrics#36]
- [x] Create cardio type enum column
- [x] Allow user to select "hike" type
- [x] Exclude "hike" type from running calculations
- [x] Display "hike" type icon
